=== fatenguettat/bticino-openwebnet/myhome-input-controller/src/main/resources/xsd/configuration.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.incalza.it/myhome/input/controller/configuration"
	xmlns="http://www.incalza.it/myhome/input/controller/configuration"
	elementFormDefault="qualified">

	<xs:element name="ConfigurationCommands">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Commands" type="commands" minOccurs="0"
					maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="command">
		<xs:choice>
			<xs:sequence>
				<xs:element name="OpenWebNetComands" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="OpenWebNetComand" type="xs:string"
								maxOccurs="unbounded" minOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="SpecialComand" type="specialComand" maxOccurs="1" />
			</xs:sequence>
		</xs:choice>
		<xs:attribute name="actionComand" type="actionComand" />
		<xs:attribute name="room" type="room" use="optional" />
	</xs:complexType>

	<xs:complexType name="commands">
		<xs:sequence>
			<xs:element name="Command" type="command" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="specialComand">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SWITCH_ROOM" />
			<xs:enumeration value="SWITCH" />
			<xs:enumeration value="PRESSED" />
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="actionComand">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON" />
			<xs:enumeration value="OFF" />
			<xs:enumeration value="NORTH_WEST" />
			<xs:enumeration value="NORTH_EAST" />
			<xs:enumeration value="NORTH" />
			<xs:enumeration value="SOUTH_WEST" />
			<xs:enumeration value="SOUTH_EAST" />
			<xs:enumeration value="SOUTH" />
			<xs:enumeration value="EAST" />
			<xs:enumeration value="WEST" />
			<xs:enumeration value="BUTTON_0" />
			<xs:enumeration value="BUTTON_1" />
			<xs:enumeration value="BUTTON_2" />
			<xs:enumeration value="BUTTON_3" />
			<xs:enumeration value="BUTTON_4" />
			<xs:enumeration value="BUTTON_5" />
			<xs:enumeration value="BUTTON_6" />
			<xs:enumeration value="BUTTON_7" />
			<xs:enumeration value="BUTTON_8" />
			<xs:enumeration value="BUTTON_9" />
			<xs:enumeration value="BUTTON_10" />
			<xs:enumeration value="BUTTON_11" />
			<xs:enumeration value="BUTTON_12" />
			<xs:enumeration value="BUTTON_13" />
			<xs:enumeration value="BUTTON_14" />
			<xs:enumeration value="BUTTON_15" />
			<xs:enumeration value="BUTTON_16" />
			<xs:enumeration value="BUTTON_17" />
			<xs:enumeration value="BUTTON_18" />
			<xs:enumeration value="BUTTON_19" />
			<xs:enumeration value="BUTTON_20" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="room">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ROOM_1" />
			<xs:enumeration value="ROOM_2" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== fatenguettat/bticino-openwebnet/myhome-input-controller/src/main/resources/configuration/configurationCommands.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConfigurationCommands
	xmlns="http://www.incalza.it/myhome/input/controller/configuration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.incalza.it/myhome/input/controller/configuration ../xsd/configuration.xsd ">
	<Commands>
		<Command actionComand="BUTTON_0">
			<SpecialComand>SWITCH_ROOM</SpecialComand>
		</Command>
		<Command actionComand="BUTTON_4">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*1*59##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="BUTTON_6">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*2*59##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="BUTTON_16">
			<OpenWebNetComands>
				<OpenWebNetComand>*1*1*58##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>		
		<Command actionComand="ON">
			<OpenWebNetComands>
				<OpenWebNetComand>*1*1*61##</OpenWebNetComand>
				<OpenWebNetComand>*1*1*62##</OpenWebNetComand>
				<OpenWebNetComand>*1*1*57##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="OFF">
			<OpenWebNetComands>
				<OpenWebNetComand>*1*0*61##</OpenWebNetComand>
				<OpenWebNetComand>*1*0*62##</OpenWebNetComand>
				<OpenWebNetComand>*1*0*57##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="SOUTH" room="ROOM_1">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*1*52##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="NORTH" room="ROOM_1">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*2*52##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="EAST" room="ROOM_1">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*1*51##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="WEST" room="ROOM_1">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*2*51##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="SOUTH" room="ROOM_2">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*1*54##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="NORTH" room="ROOM_2">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*2*54##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="WEST" room="ROOM_2">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*1*53##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
		<Command actionComand="EAST" room="ROOM_2">
			<OpenWebNetComands>
				<OpenWebNetComand>*2*2*53##</OpenWebNetComand>
			</OpenWebNetComands>
		</Command>
	</Commands>
</ConfigurationCommands>
